#!/usr/bin/env python3
"""
Test FACE DE-PIXELATION + TATTOO CONSISTENCY + FACIAL FEATURE IMPROVEMENTS
"""

import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent))

from src.image.luna_generator import generate_luna_scenario, generate_luna_selfie

print("=" * 80)
print("🧪 TESTING FACE DE-PIXELATION + TATTOO + FACIAL FEATURES")
print("=" * 80)
print("\n🎨 IMPROVEMENTS MADE:")
print()
print("1️⃣ FACE DE-PIXELATION:")
print("   BASE DESCRIPTION:")
print("   • Added: 'long black lashes' (eye detail)")
print("   • Added: 'visible pores' (skin texture)")
print("   • Added: 'delicate jawline' (face structure)")
print("   • Added: 'dark plum matte lipstick' (lip detail)")
print("   • Added: 'small straight nose' (nose detail)")
print("   • Added: 'sharp facial details' (overall sharpness)")
print()
print("   GENERATION PROMPTS:")
print("   • Added: 'sharp detailed face'")
print("   • Added: 'crisp facial features'")
print("   • Added: 'high detail eyes and lips'")
print("   • Changed: '8K' → '8K ultra HD'")
print()
print("   NEGATIVE PROMPTS:")
print("   • Added: 'pixelated face' (blocks face pixelation)")
print("   • Added: 'pixelated skin' (blocks skin pixelation)")
print("   • Added: 'low resolution face' (blocks low-res)")
print("   • Added: 'blurry face' (blocks blur)")
print("   • Added: 'blurred eyes' (blocks eye blur)")
print("   • Added: 'blurred features' (blocks feature blur)")
print("   • Added: 'soft focus face' (blocks soft focus)")
print("   • Added: 'low detail face' (blocks low detail)")
print("   • Added: 'deformed face' (blocks face deformation)")
print("   • Added: 'asymmetric face' (blocks asymmetry)")
print("   • Added: 'crooked nose' (blocks nose issues)")
print("   • Added: 'deformed eyes' (blocks eye issues)")
print()
print("2️⃣ TATTOO CONSISTENCY:")
print("   BASE DESCRIPTION:")
print("   • Changed: 'single small simple black line art snake tattoo on right forearm only'")
print("   • To: 'single small minimalist black outline snake tattoo on outer right forearm 8cm below elbow facing forward no other tattoos anywhere'")
print()
print("   IMPROVEMENTS:")
print("   ✓ 'minimalist black outline' (specific style)")
print("   ✓ 'outer right forearm' (exact location)")
print("   ✓ '8cm below elbow' (precise placement)")
print("   ✓ 'facing forward' (orientation)")
print("   ✓ 'no other tattoos anywhere' (exclusivity)")
print()
print("   GENERATION PROMPTS:")
print("   • Changed: 'single snake tattoo right forearm'")
print("   • To: 'single small black snake tattoo on right forearm only'")
print()
print("   NEGATIVE PROMPTS:")
print("   • Added: 'left arm tattoos' (blocks wrong arm)")
print("   • Added: 'tribal tattoos' (blocks wrong style)")
print("   • Kept: face, neck, chest, breast, stomach, back, leg tattoos blocked")
print()
print("3️⃣ FACIAL FEATURE CONSISTENCY:")
print("   ADDED SPECIFIC DETAILS:")
print("   ✓ 'long black lashes' (eyelash detail)")
print("   ✓ 'delicate jawline' (jaw structure)")
print("   ✓ 'small straight nose' (nose shape)")
print("   ✓ 'dark plum matte lipstick' (lip finish)")
print("   ✓ 'visible pores' (skin realism)")
print("   ✓ 'sharp facial details' (overall clarity)")
print()
print("=" * 80)

# Test 1: Selfie (primary face test)
print("\n1. Testing sultry selfie (primary face detail test)...")
try:
    image_bytes = generate_luna_selfie(mood="sultry", nsfw=False)
    print(f"   ✅ Generated: {len(image_bytes):,} bytes")
    print(f"   → Check: Sharp detailed face, crisp features, high detail eyes/lips")
except Exception as e:
    print(f"   ❌ Failed: {e}")

# Test 2: Topless (face + tattoo + nipples)
print("\n2. Testing topless photo (face + tattoo + nipples)...")
try:
    image_bytes = generate_luna_scenario(scenario_type="topless", nsfw=True)
    print(f"   ✅ Generated: {len(image_bytes):,} bytes")
    print(f"   → Check: Sharp face, single snake tattoo right forearm, light pink nipples")
except Exception as e:
    print(f"   ❌ Failed: {e}")

# Test 3: Full body nude (overall consistency)
print("\n3. Testing full body nude (overall consistency check)...")
try:
    image_bytes = generate_luna_scenario(scenario_type="fullbody", nsfw=True)
    print(f"   ✅ Generated: {len(image_bytes):,} bytes")
    print(f"   → Check: Sharp facial features, single tattoo right forearm only")
except Exception as e:
    print(f"   ❌ Failed: {e}")

# Test 4: Mirror selfie (tattoo visibility)
print("\n4. Testing mirror selfie (tattoo visibility test)...")
try:
    image_bytes = generate_luna_scenario(scenario_type="mirror", nsfw=True)
    print(f"   ✅ Generated: {len(image_bytes):,} bytes")
    print(f"   → Check: Single small black snake on right forearm, no other tattoos")
except Exception as e:
    print(f"   ❌ Failed: {e}")

# Test 5: Lying nude (close-up potential)
print("\n5. Testing lying nude (face + body detail)...")
try:
    image_bytes = generate_luna_scenario(scenario_type="nude_lying", nsfw=True)
    print(f"   ✅ Generated: {len(image_bytes):,} bytes")
    print(f"   → Check: Crisp facial features, high detail eyes, sharp face")
except Exception as e:
    print(f"   ❌ Failed: {e}")

# Test 6: Seductive selfie (facial detail focus)
print("\n6. Testing seductive selfie (facial detail focus)...")
try:
    image_bytes = generate_luna_selfie(mood="seductive", nsfw=True)
    print(f"   ✅ Generated: {len(image_bytes):,} bytes")
    print(f"   → Check: Sharp detailed face, long black lashes, plum matte lips")
except Exception as e:
    print(f"   ❌ Failed: {e}")

print("\n" + "=" * 80)
print("✅ FACE + TATTOO + FEATURES TEST COMPLETE")
print("=" * 80)
print("\n🔍 EXPECTED RESULTS:")
print()
print("FACE DE-PIXELATION:")
print("  ✓ Sharp, crisp facial features (not pixelated)")
print("  ✓ High detail eyes with long black lashes")
print("  ✓ High detail lips with dark plum matte lipstick")
print("  ✓ Visible skin texture and pores (not smooth/airbrushed)")
print("  ✓ Delicate jawline clearly defined")
print("  ✓ Small straight nose")
print("  ✓ 8K ultra HD quality")
print()
print("TATTOO CONSISTENCY:")
print("  ✓ Single small minimalist black outline snake")
print("  ✓ Located on outer right forearm")
print("  ✓ 8cm below elbow")
print("  ✓ Facing forward")
print("  ✓ NO tattoos on: left arm, face, neck, chest, breasts, stomach, back, legs")
print("  ✓ NO other tattoos anywhere else")
print()
print("FACIAL FEATURES:")
print("  ✓ Almond-shaped bright violet purple eyes")
print("  ✓ Long black lashes")
print("  ✓ Thick black winged eyeliner")
print("  ✓ Heart-shaped face")
print("  ✓ High defined cheekbones")
print("  ✓ Delicate jawline")
print("  ✓ Small straight nose")
print("  ✓ Full pouty lips")
print("  ✓ Dark plum matte lipstick")
print("  ✓ Very pale porcelain skin")
print("  ✓ Visible pores and natural texture")
print()
print("KEY IMPROVEMENTS:")
print("  🎨 Face is now SHARP and DETAILED (not pixelated)")
print("  🎨 Tattoo is PRECISELY DEFINED (right forearm only, 8cm below elbow)")
print("  🎨 Facial features are ULTRA-SPECIFIC (lashes, nose, jawline, lip finish)")
print("  🎨 Comprehensive negative prompts block all variations")
print("  🎨 8K ultra HD quality for maximum clarity")

